/**
 * pm2 process supervisor commands: setup, start, stop, restart, status, logs.
 *
 * Provides `comis pm2 [setup|start|stop|restart|status|logs]` subcommands
 * for managing the Comis daemon via pm2 as an optional cross-platform
 * process supervisor (alternative to systemd on macOS/WSL).
 *
 * @module
 */

import type { Command } from "commander";
import { execFile, spawn } from "node:child_process";
import { existsSync, writeFileSync, mkdirSync } from "node:fs";
import * as os from "node:os";
import { promisify } from "node:util";
import { safePath } from "@comis/core";
import { success, error, info, warn } from "../output/format.js";

const exec = promisify(execFile);

const COMIS_DIR = safePath(os.homedir(), ".comis");
const ECOSYSTEM_FILE = safePath(COMIS_DIR, "ecosystem.config.js");

/**
 * Ensure pm2 is installed and available on PATH.
 *
 * @returns The pm2 version string
 */
async function ensurePm2(): Promise<string> {
  try {
    const { stdout } = await exec("pm2", ["--version"]);
    return stdout.trim();
  } catch {
    error("pm2 not found. Install with: npm install -g pm2");
    process.exit(1);
  }
}

/**
 * Run a pm2 command and return its output.
 *
 * @param args - Arguments to pass to the pm2 binary
 * @returns stdout and stderr from the pm2 process
 */
async function runPm2(...args: string[]): Promise<{ stdout: string; stderr: string }> {
  try {
    return await exec("pm2", args);
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    error(`pm2 command failed: ${msg}`);
    process.exit(1);
  }
}

/** Handle the `pm2 setup` subcommand — generate ecosystem config file. */
async function handleSetup(): Promise<void> {
  await ensurePm2();

  const daemonPath = new URL("../../../daemon/dist/daemon.js", import.meta.url).pathname;
  if (!existsSync(daemonPath)) {
    error("Daemon binary not found. Run `pnpm build` first.");
    process.exit(1);
  }

  // eslint-disable-next-line no-restricted-syntax -- CLI bootstrap before SecretManager
  const configPaths = process.env["COMIS_CONFIG_PATHS"] ?? safePath(os.homedir(), ".comis/config.yaml");

  const content = `// Comis pm2 ecosystem config — generated by \`comis pm2 setup\`
module.exports = {
  apps: [{
    name: "comis",
    script: ${JSON.stringify(daemonPath)},
    node_args: ["--max-old-space-size=512"],
    env: {
      COMIS_CONFIG_PATHS: ${JSON.stringify(configPaths)},
    },
    restart_delay: 2000,
    kill_timeout: 10000,
    max_restarts: 10,
    autorestart: true,
  }],
};
`;

  mkdirSync(COMIS_DIR, { recursive: true, mode: 0o700 });
  writeFileSync(ECOSYSTEM_FILE, content, { mode: 0o600 });
  success("Ecosystem file written to " + ECOSYSTEM_FILE);
  info("Start with: comis pm2 start");
}

/** Handle the `pm2 start` subcommand. */
async function handleStart(): Promise<void> {
  await ensurePm2();
  if (!existsSync(ECOSYSTEM_FILE)) {
    error("Ecosystem file not found. Run `comis pm2 setup` first.");
    process.exit(1);
  }
  await runPm2("start", ECOSYSTEM_FILE);
  success("Daemon started via pm2");
}

/** Handle the `pm2 stop` subcommand. */
async function handleStop(): Promise<void> {
  await ensurePm2();
  await runPm2("stop", "comis");
  success("Daemon stopped");
}

/** Handle the `pm2 restart` subcommand. */
async function handleRestart(): Promise<void> {
  await ensurePm2();
  await runPm2("restart", "comis");
  success("Daemon restarted");
}

/** Handle the `pm2 status` subcommand. */
async function handleStatus(): Promise<void> {
  await ensurePm2();
  try {
    const { stdout } = await exec("pm2", ["describe", "comis"]);
    console.log(stdout);
  } catch {
    warn("Daemon not managed by pm2. Run `comis pm2 setup && comis pm2 start` first.");
  }
}

/** Handle the `pm2 logs` subcommand. */
function handleLogs(options: { lines: string }): void {
  void ensurePm2().then(() => {
    const child = spawn("pm2", ["logs", "comis", "--lines", options.lines], {
      stdio: "inherit",
    });
    child.on("error", (err) => {
      error(`Failed to stream logs: ${err.message}`);
      process.exit(1);
    });
  });
}

// ---------- Command registration ----------

/**
 * Register the `pm2` subcommand group on the program.
 *
 * @param program - The root Commander program
 */
export function registerPm2Command(program: Command): void {
  const pm2 = program.command("pm2").description("Manage daemon via pm2 process supervisor");

  pm2.command("setup").description("Generate pm2 ecosystem config").action(handleSetup);
  pm2.command("start").description("Start daemon via pm2").action(handleStart);
  pm2.command("stop").description("Stop daemon via pm2").action(handleStop);
  pm2.command("restart").description("Restart daemon via pm2").action(handleRestart);
  pm2.command("status").description("Show pm2 process status").action(handleStatus);
  pm2.command("logs")
    .description("Stream daemon logs via pm2")
    .option("-n, --lines <n>", "Number of recent lines to show", "50")
    .action(handleLogs);
}
