// SPDX-License-Identifier: Apache-2.0
/**
 * Pure-function emitter: converts a JSON Schema map into the
 * dispatch-table TypeScript source for
 * `packages/web/src/api/contracts.generated.ts`.
 *
 * Browser-safety invariants the emitted source MUST honor:
 *   - No `@comis/*` imports.
 *   - No `node:*` imports.
 *   - No Zod runtime.
 *   - Only browser-safe primitives in the validator (typeof, Array.isArray,
 *     Object.keys, Object.entries, Number.isInteger, Number.isNaN).
 *
 * Determinism invariants:
 *   - Single sort by method-name (caller passes a pre-sorted map; we preserve
 *     iteration order via Object.keys on string-keyed plain objects).
 *   - No Date.now / new Date / UUID / Math.random / process.version in the
 *     emitted source.
 *   - JSON.stringify with 2-space indentation matches the JSON sibling
 *     artifact's indentation for diff symmetry.
 *
 * @module
 */

/**
 * Per-contract JSON Schema entry — matches the shape the codegen entry point
 * writes into `contracts.generated.json`.
 */
export interface JsonSchemaContractEntry {
  /** JSON Schema for the request payload. */
  readonly request: unknown;
  /** JSON Schema for the response payload. */
  readonly response: unknown;
  /** Trust scopes the method is registered under. */
  readonly scopes: readonly string[];
}

/** Map keyed by RPC method name (caller MUST pass keys in alphabetical order). */
export type JsonSchemaMap = Readonly<Record<string, JsonSchemaContractEntry>>;

/**
 * Emit the dispatch-table TS source. Caller passes the already-sorted map and
 * the SPDX/AUTOGENERATED/eslint-disable header is prepended here.
 *
 * @param sortedMap  JSON Schema map; keys MUST be alphabetically sorted.
 * @returns          The complete TS source for `contracts.generated.ts`.
 */
export function emitDispatchTableTs(sortedMap: JsonSchemaMap): string {
  const header = `// SPDX-License-Identifier: Apache-2.0
/* AUTOGENERATED — do not edit. Run \`pnpm contracts:generate\`. */
/* eslint-disable */
`;

  const types = `
// ---------------------------------------------------------------------------
// JSON Schema node type — inlined to avoid any @comis/* or node:* import.
// Mirrors the subset of JSON Schema 7 the contract registry actually emits
// after the 12-shape allowlist (scripts/contracts/supported-zod-shapes.ts).
// ---------------------------------------------------------------------------

export type JsonSchemaNode =
  | { readonly type: "string"; readonly minLength?: number; readonly maxLength?: number; readonly format?: string; readonly const?: string; readonly enum?: readonly string[] }
  | { readonly type: "number"; readonly minimum?: number; readonly maximum?: number; readonly const?: number }
  | { readonly type: "integer"; readonly minimum?: number; readonly maximum?: number }
  | { readonly type: "boolean"; readonly const?: boolean }
  | { readonly type: "null" }
  | { readonly type: "object"; readonly properties?: Readonly<Record<string, JsonSchemaNode>>; readonly required?: readonly string[]; readonly additionalProperties?: boolean | JsonSchemaNode; readonly propertyNames?: JsonSchemaNode }
  | { readonly type: "array"; readonly items: JsonSchemaNode }
  | { readonly anyOf: readonly JsonSchemaNode[] }
  | { readonly oneOf: readonly JsonSchemaNode[] }
  | { readonly const: unknown }
  | { readonly enum: readonly unknown[] }
  | Record<string, unknown>;

export interface ContractMeta {
  readonly request: JsonSchemaNode;
  readonly response: JsonSchemaNode;
  readonly scopes: readonly string[];
}

// ---------------------------------------------------------------------------
// JSON Schema -> TypeScript projection for the generated RPC method map.
// The generator emits each schema as a literal, so method names, params, and
// results stay tied to the one API contract registry without browser imports.
// ---------------------------------------------------------------------------

type SchemaProperties<S> = S extends { readonly properties: infer P }
  ? P extends Readonly<Record<string, unknown>>
    ? P
    : Record<never, never>
  : Record<never, never>;

type SchemaRequiredKeys<S> = S extends {
  readonly required: readonly (infer K)[];
}
  ? Extract<K, keyof SchemaProperties<S>>
  : never;

type JsonObjectValue<S> = {
  [K in SchemaRequiredKeys<S>]-?: JsonSchemaValue<SchemaProperties<S>[K]>;
} & {
  [K in Exclude<keyof SchemaProperties<S>, SchemaRequiredKeys<S>>]?:
    JsonSchemaValue<SchemaProperties<S>[K]>;
} & (S extends { readonly additionalProperties: infer A }
  ? A extends false
    ? unknown
    : A extends Readonly<Record<string, unknown>>
      ? Readonly<Record<string, JsonSchemaValue<A>>>
      : Readonly<Record<string, unknown>>
  : Readonly<Record<string, unknown>>);

export type JsonSchemaValue<S> =
  S extends { readonly anyOf: readonly (infer A)[] }
    ? JsonSchemaValue<A>
    : S extends { readonly oneOf: readonly (infer O)[] }
      ? JsonSchemaValue<O>
      : S extends { readonly const: infer C }
        ? C
        : S extends { readonly enum: readonly (infer E)[] }
          ? E
          : S extends { readonly type: "string" }
            ? string
            : S extends { readonly type: "number" | "integer" }
              ? number
              : S extends { readonly type: "boolean" }
                ? boolean
                : S extends { readonly type: "null" }
                  ? null
                  : S extends { readonly type: "array"; readonly items: infer I }
                    ? JsonSchemaValue<I>[]
                    : S extends { readonly type: "object" }
                      ? JsonObjectValue<S>
                      : unknown;
`;

  const validator = `
// ---------------------------------------------------------------------------
// Hand-rolled validator — runs in browser; zero external deps.
// Returns true iff \`v\` matches \`node\`. Errors are caller-side (the caller
// distinguishes request vs. response and surfaces a method-named error).
// ---------------------------------------------------------------------------

function validateNode(node: JsonSchemaNode, v: unknown): boolean {
  if (node === null || typeof node !== "object") return false;
  const n = node as Record<string, unknown>;
  if (Array.isArray(n.anyOf)) {
    return (n.anyOf as JsonSchemaNode[]).some((sub) => validateNode(sub, v));
  }
  if (Array.isArray(n.oneOf)) {
    const matches = (n.oneOf as JsonSchemaNode[]).filter((sub) => validateNode(sub, v));
    return matches.length === 1;
  }
  if (n.const !== undefined && n.type === undefined) {
    return v === n.const;
  }
  if (Array.isArray(n.enum) && n.type === undefined) {
    return (n.enum as unknown[]).includes(v);
  }
  switch (n.type) {
    case "string": {
      if (typeof v !== "string") return false;
      if (typeof n.minLength === "number" && v.length < n.minLength) return false;
      if (typeof n.maxLength === "number" && v.length > n.maxLength) return false;
      if (n.const !== undefined && v !== n.const) return false;
      if (Array.isArray(n.enum) && !(n.enum as string[]).includes(v)) return false;
      return true;
    }
    case "number": {
      if (typeof v !== "number" || Number.isNaN(v)) return false;
      if (typeof n.minimum === "number" && v < n.minimum) return false;
      if (typeof n.maximum === "number" && v > n.maximum) return false;
      if (n.const !== undefined && v !== n.const) return false;
      return true;
    }
    case "integer": {
      if (typeof v !== "number" || !Number.isInteger(v)) return false;
      if (typeof n.minimum === "number" && v < n.minimum) return false;
      if (typeof n.maximum === "number" && v > n.maximum) return false;
      return true;
    }
    case "boolean": {
      if (typeof v !== "boolean") return false;
      if (n.const !== undefined && v !== n.const) return false;
      return true;
    }
    case "null":
      return v === null;
    case "object": {
      if (typeof v !== "object" || v === null || Array.isArray(v)) return false;
      const obj = v as Record<string, unknown>;
      const required = (n.required as string[] | undefined) ?? [];
      for (const k of required) if (!(k in obj)) return false;
      const props = (n.properties as Record<string, JsonSchemaNode> | undefined) ?? {};
      for (const [k, schema] of Object.entries(props)) {
        if (k in obj && !validateNode(schema, obj[k])) return false;
      }
      if (n.additionalProperties === false) {
        const known = new Set(Object.keys(props));
        for (const k of Object.keys(obj)) if (!known.has(k)) return false;
      } else if (typeof n.additionalProperties === "object" && n.additionalProperties !== null) {
        const known = new Set(Object.keys(props));
        const addlSchema = n.additionalProperties as JsonSchemaNode;
        for (const k of Object.keys(obj)) {
          if (known.has(k)) continue;
          if (!validateNode(addlSchema, obj[k])) return false;
        }
      }
      return true;
    }
    case "array": {
      if (!Array.isArray(v)) return false;
      const items = n.items as JsonSchemaNode | undefined;
      if (!items) return true;
      return v.every((item) => validateNode(items, item));
    }
    default:
      // Permissive fallback for schemas with no \`type\` (e.g., empty object
      // schema {} produced by z.unknown() inside a record value-type).
      return true;
  }
}
`;

  // JSON.stringify with 2-space indent — matches the JSON sibling artifact.
  // No `as const` on the literal because TypeScript can't infer the union
  // types from arbitrary JSON. Cast it explicitly to the typed Record.
  const contractsJson = JSON.stringify(sortedMap, null, 2);

  const constants = `
// ---------------------------------------------------------------------------
// CONTRACTS table — alphabetically sorted by method name (deterministic).
// Generated from API_CONTRACTS_ORDERED via z.toJSONSchema(...,
// { unrepresentable: "throw", reused: "inline" }).
// ---------------------------------------------------------------------------

export const CONTRACTS = ${contractsJson} as const satisfies Readonly<Record<string, ContractMeta>>;

export type WebRpcMethodMap = {
  readonly [M in keyof typeof CONTRACTS]: {
    readonly params: JsonSchemaValue<(typeof CONTRACTS)[M]["request"]>;
    readonly result: JsonSchemaValue<(typeof CONTRACTS)[M]["response"]>;
  };
};

export type MethodName = keyof WebRpcMethodMap;

// ---------------------------------------------------------------------------
// Public validators — delegate to validateNode against the request/response
// JSON Schema literal for the method. Designed for browser use; the wrapping
// caller distinguishes request vs. response.
// ---------------------------------------------------------------------------

export function validateRequest(method: MethodName, v: unknown): boolean {
  const entry = CONTRACTS[method];
  return validateNode(entry.request, v);
}

export function validateResponse(method: MethodName, v: unknown): boolean {
  const entry = CONTRACTS[method];
  return validateNode(entry.response, v);
}
`;

  // Single trailing newline (POSIX text-file convention; matches JSON sibling).
  return header + types + validator + constants;
}
