// SPDX-License-Identifier: Apache-2.0
/**
 * Codegen unit tests — exercise the `generate-web-artifact.ts` pipeline.
 *
 * Phase 35 Wave D Plan 35-20.
 *
 * Test coverage:
 *   1. `runCodegen()` writes all three artifacts and returns the result.
 *   2. Double-run output is byte-identical (sha256 hash compare).
 *   3. Size report is within budget on the real registry (190 contracts).
 *   4. The allowlist gate triggers — `assertOnlyAllowlistShapes` throws on
 *      a synthetic forbidden Zod shape (e.g., `z.date()`).
 *   5. `unrepresentable: "throw"` is wired through — codegen on a
 *      synthetic `z.date()` contract throws at `z.toJSONSchema` time
 *      (defense in depth alongside the allowlist gate).
 *
 * The tests do NOT mock `@comis/core` — they run against the real Wave C
 * registry to ensure the budget assertion is meaningful at production scale.
 *
 * @module
 */
import { describe, it, expect, beforeAll } from "vitest";
import { readFileSync, statSync } from "node:fs";
import { createHash } from "node:crypto";
import { z } from "zod";
import { runCodegen, OUT_TS, OUT_JSON, OUT_SIZE } from "./generate-web-artifact.js";
import { assertOnlyAllowlistShapes } from "./walk-zod-schema.js";
import {
  BUDGET_MINIFIED_BYTES,
  BUDGET_GZIPPED_BYTES,
} from "./size-budget.js";

function sha256(buf: Buffer | string): string {
  return createHash("sha256")
    .update(buf as Buffer)
    .digest("hex");
}

describe("scripts/contracts/generate-web-artifact (Plan 35-20)", () => {
  describe("runCodegen()", () => {
    let result: ReturnType<typeof runCodegen>;

    beforeAll(() => {
      result = runCodegen();
    });

    it("produces all three artifacts on disk", () => {
      expect(statSync(OUT_TS).isFile()).toBe(true);
      expect(statSync(OUT_JSON).isFile()).toBe(true);
      expect(statSync(OUT_SIZE).isFile()).toBe(true);
    });

    it("returns a non-empty CodegenResult", () => {
      expect(typeof result.tsSource).toBe("string");
      expect(result.tsSource.length).toBeGreaterThan(0);
      expect(Object.keys(result.jsonSchemaMap).length).toBeGreaterThan(0);
      expect(typeof result.sizeReport.totalMinified).toBe("number");
    });

    it("emits AUTOGENERATED + eslint-disable banners (Pitfall 8)", () => {
      expect(result.tsSource).toContain("AUTOGENERATED");
      expect(result.tsSource).toContain("eslint-disable");
      expect(result.tsSource).toContain("SPDX-License-Identifier");
    });

    it("emits no @comis/* or node:* imports in the TS source (WEB-CONTRACTS-15)", () => {
      // Generated file has zero imports — the validator and JSON Schema node
      // type are inlined. Defends the browser-safety invariant.
      expect(result.tsSource).not.toMatch(/from\s+["']node:/);
      expect(result.tsSource).not.toMatch(/from\s+["']@comis\//);
      expect(result.tsSource).not.toMatch(/from\s+["']zod["']/);
    });

    it("sorts CONTRACTS keys alphabetically by method name (RESEARCH determinism rule)", () => {
      const keys = Object.keys(result.jsonSchemaMap);
      const sorted = [...keys].sort((a, b) => a.localeCompare(b));
      expect(keys).toEqual(sorted);
    });
  });

  describe("double-run determinism (RESEARCH RES-PIT-19)", () => {
    it("produces byte-identical output across two runs", () => {
      runCodegen();
      const ts1 = readFileSync(OUT_TS);
      const json1 = readFileSync(OUT_JSON);
      const size1 = readFileSync(OUT_SIZE);

      runCodegen();
      const ts2 = readFileSync(OUT_TS);
      const json2 = readFileSync(OUT_JSON);
      const size2 = readFileSync(OUT_SIZE);

      expect(sha256(ts2), "contracts.generated.ts diverged on rerun").toBe(sha256(ts1));
      expect(sha256(json2), "contracts.generated.json diverged on rerun").toBe(
        sha256(json1),
      );
      expect(sha256(size2), "contracts.generated.size.json diverged on rerun").toBe(
        sha256(size1),
      );
    });
  });

  describe("bundle-size budget (CONTEXT D-02)", () => {
    it("real registry fits within 120 KB minified + 38 KB gzipped", () => {
      const result = runCodegen();
      expect(
        result.sizeReport.totalMinified,
        `minified ${result.sizeReport.totalMinified}B exceeds budget ${BUDGET_MINIFIED_BYTES}B`,
      ).toBeLessThanOrEqual(BUDGET_MINIFIED_BYTES);
      expect(
        result.sizeReport.totalGzipped,
        `gzipped ${result.sizeReport.totalGzipped}B exceeds budget ${BUDGET_GZIPPED_BYTES}B`,
      ).toBeLessThanOrEqual(BUDGET_GZIPPED_BYTES);
      expect(result.sizeReport.overBudget).toBe(false);
    });
  });

  describe("allowlist gate (WEB-CONTRACTS-11 + BLOCKER 5)", () => {
    it("rejects z.date() (forbidden shape) via assertOnlyAllowlistShapes", () => {
      // `z.date()` constructs ZodDate — NOT in the 12-shape allowlist.
      // The walker should throw with method + direction + class name.
      const synthetic = z.object({ when: z.date() });
      expect(() =>
        assertOnlyAllowlistShapes("synthetic.method", "request", synthetic),
      ).toThrow(/ZodDate|forbidden Zod shape/);
    });

    it("rejects z.lazy(() => ...) (forbidden shape) via assertOnlyAllowlistShapes", () => {
      const synthetic = z.lazy(() => z.string());
      expect(() =>
        assertOnlyAllowlistShapes("synthetic.method", "request", synthetic),
      ).toThrow(/ZodLazy|forbidden Zod shape/);
    });

    it("rejects z.string().regex(...) refinement chain at compile time", () => {
      // Refinements project to `pattern` in JSON Schema, but the underlying
      // class is still ZodString (terminal scalar shape — accepted by the
      // walker). The allowlist gate's intent is to reject custom-shape
      // schemas (ZodEffects, ZodTransform, ZodLazy, ZodDate, ZodTuple, etc.).
      // We assert this passes (well within the allowlist) AND emits valid
      // JSON Schema for the regex.
      const synthetic = z.object({ key: z.string().regex(/^[a-z]+$/) });
      expect(() =>
        assertOnlyAllowlistShapes("synthetic.method", "request", synthetic),
      ).not.toThrow();
    });
  });

  describe("z.toJSONSchema unrepresentable: 'throw' (CONTEXT D-06 + BLOCKER 5)", () => {
    it("throws on a synthetic z.date() schema (defense-in-depth)", () => {
      // If the allowlist gate is removed or bypassed, the codegen step
      // STILL throws at z.toJSONSchema time — `unrepresentable: "throw"`
      // is the second line of defense.
      const synthetic = z.object({ when: z.date() });
      expect(() =>
        z.toJSONSchema(synthetic, { unrepresentable: "throw", reused: "inline" }),
      ).toThrow();
    });
  });
});
