// SPDX-License-Identifier: Apache-2.0
/**
 * Codegen unit tests — exercise the `generate-web-artifact.ts` pipeline.
 *
 * Test coverage:
 *   1. `runCodegen()` writes all three artifacts and returns the result.
 *   2. Double-run output is byte-identical (sha256 hash compare).
 *   3. Size report is within budget on the real registry (190 contracts).
 *   4. The allowlist gate triggers — `assertOnlyAllowlistShapes` throws on
 *      a synthetic forbidden Zod shape (e.g., `z.date()`).
 *   5. `unrepresentable: "throw"` is wired through — codegen on a
 *      synthetic `z.date()` contract throws at `z.toJSONSchema` time
 *      (defense in depth alongside the allowlist gate).
 *
 * The tests do NOT mock `@comis/core` — they run against the real registry
 * to ensure the budget assertion is meaningful at production scale.
 *
 * @module
 */
import { describe, it, expect, beforeAll, afterAll } from "vitest";
import { readFileSync, statSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { createHash } from "node:crypto";
import { z } from "zod";
import { runCodegen } from "./generate-web-artifact.js";
import { assertOnlyAllowlistShapes } from "./walk-zod-schema.js";
import {
  BUDGET_MINIFIED_BYTES,
  BUDGET_GZIPPED_BYTES,
} from "./size-budget.js";

function sha256(buf: Buffer | string): string {
  return createHash("sha256")
    .update(buf as Buffer)
    .digest("hex");
}

// Write all artifacts to a per-suite temp dir, never the committed
// packages/web/src/api paths. test/architecture/contract-codegen-drift.test.ts
// runs in a SEPARATE vitest project (parallel fork) and also calls
// runCodegen(); writing the shared committed files from both projects
// concurrently let one read the other's in-progress write (a spurious drift
// flake). Redirecting to a temp dir removes the cross-project race surface.
let OUT_DIR: string;
const OUT_TS = (): string => join(OUT_DIR, "contracts.generated.ts");
const OUT_JSON = (): string => join(OUT_DIR, "contracts.generated.json");
const OUT_SIZE = (): string => join(OUT_DIR, "contracts.generated.size.json");

describe("scripts/contracts/generate-web-artifact", () => {
  beforeAll(() => {
    OUT_DIR = mkdtempSync(join(tmpdir(), "comis-codegen-gen-"));
  });
  afterAll(() => {
    rmSync(OUT_DIR, { recursive: true, force: true });
  });

  describe("runCodegen()", () => {
    let result: ReturnType<typeof runCodegen>;

    beforeAll(() => {
      result = runCodegen(OUT_DIR);
    });

    it("produces all three artifacts on disk", () => {
      expect(statSync(OUT_TS()).isFile()).toBe(true);
      expect(statSync(OUT_JSON()).isFile()).toBe(true);
      expect(statSync(OUT_SIZE()).isFile()).toBe(true);
    });

    it("returns a non-empty CodegenResult", () => {
      expect(typeof result.tsSource).toBe("string");
      expect(result.tsSource.length).toBeGreaterThan(0);
      expect(Object.keys(result.jsonSchemaMap).length).toBeGreaterThan(0);
      expect(typeof result.sizeReport.totalMinified).toBe("number");
    });

    it("emits AUTOGENERATED + eslint-disable banners", () => {
      expect(result.tsSource).toContain("AUTOGENERATED");
      expect(result.tsSource).toContain("eslint-disable");
      expect(result.tsSource).toContain("SPDX-License-Identifier");
    });

    it("emits no @comis/* or node:* imports in the TS source", () => {
      // Generated file has zero imports — the validator and JSON Schema node
      // type are inlined. Defends the browser-safety invariant.
      expect(result.tsSource).not.toMatch(/from\s+["']node:/);
      expect(result.tsSource).not.toMatch(/from\s+["']@comis\//);
      expect(result.tsSource).not.toMatch(/from\s+["']zod["']/);
    });

    it("sorts CONTRACTS keys alphabetically by method name (determinism rule)", () => {
      const keys = Object.keys(result.jsonSchemaMap);
      const sorted = [...keys].sort((a, b) => a.localeCompare(b));
      expect(keys).toEqual(sorted);
    });
  });

  describe("double-run determinism", () => {
    it("produces byte-identical output across two runs", () => {
      runCodegen(OUT_DIR);
      const ts1 = readFileSync(OUT_TS());
      const json1 = readFileSync(OUT_JSON());
      const size1 = readFileSync(OUT_SIZE());

      runCodegen(OUT_DIR);
      const ts2 = readFileSync(OUT_TS());
      const json2 = readFileSync(OUT_JSON());
      const size2 = readFileSync(OUT_SIZE());

      expect(sha256(ts2), "contracts.generated.ts diverged on rerun").toBe(sha256(ts1));
      expect(sha256(json2), "contracts.generated.json diverged on rerun").toBe(
        sha256(json1),
      );
      expect(sha256(size2), "contracts.generated.size.json diverged on rerun").toBe(
        sha256(size1),
      );
    });
  });

  describe("bundle-size budget", () => {
    it("real registry fits within the configured minified and gzipped budgets", () => {
      const result = runCodegen(OUT_DIR);
      expect(
        result.sizeReport.totalMinified,
        `minified ${result.sizeReport.totalMinified}B exceeds budget ${BUDGET_MINIFIED_BYTES}B`,
      ).toBeLessThanOrEqual(BUDGET_MINIFIED_BYTES);
      expect(
        result.sizeReport.totalGzipped,
        `gzipped ${result.sizeReport.totalGzipped}B exceeds budget ${BUDGET_GZIPPED_BYTES}B`,
      ).toBeLessThanOrEqual(BUDGET_GZIPPED_BYTES);
      expect(result.sizeReport.overBudget).toBe(false);
    });
  });

  describe("allowlist gate", () => {
    it("rejects z.date() (forbidden shape) via assertOnlyAllowlistShapes", () => {
      // `z.date()` constructs ZodDate — NOT in the 12-shape allowlist.
      // The walker should throw with method + direction + class name.
      const synthetic = z.object({ when: z.date() });
      expect(() =>
        assertOnlyAllowlistShapes("synthetic.method", "request", synthetic),
      ).toThrow(/ZodDate|forbidden Zod shape/);
    });

    it("rejects z.lazy(() => ...) (forbidden shape) via assertOnlyAllowlistShapes", () => {
      const synthetic = z.lazy(() => z.string());
      expect(() =>
        assertOnlyAllowlistShapes("synthetic.method", "request", synthetic),
      ).toThrow(/ZodLazy|forbidden Zod shape/);
    });

    it("rejects z.string().regex(...) refinement chain at compile time", () => {
      // Refinements project to `pattern` in JSON Schema, but the underlying
      // class is still ZodString (terminal scalar shape — accepted by the
      // walker). The allowlist gate's intent is to reject custom-shape
      // schemas (ZodEffects, ZodTransform, ZodLazy, ZodDate, ZodTuple, etc.).
      // We assert this passes (well within the allowlist) AND emits valid
      // JSON Schema for the regex.
      const synthetic = z.object({ key: z.string().regex(/^[a-z]+$/) });
      expect(() =>
        assertOnlyAllowlistShapes("synthetic.method", "request", synthetic),
      ).not.toThrow();
    });
  });

  describe("z.toJSONSchema unrepresentable: 'throw'", () => {
    it("throws on a synthetic z.date() schema (defense-in-depth)", () => {
      // If the allowlist gate is removed or bypassed, the codegen step
      // STILL throws at z.toJSONSchema time — `unrepresentable: "throw"`
      // is the second line of defense.
      const synthetic = z.object({ when: z.date() });
      expect(() =>
        z.toJSONSchema(synthetic, { unrepresentable: "throw", reused: "inline" }),
      ).toThrow();
    });
  });
});
