// SPDX-License-Identifier: Apache-2.0
/**
 * Config writer for wizard results.
 *
 * Converts WizardResult into a valid config.yaml and .env file
 * using the yaml library's stringify (not hand-rolled YAML).
 * Uses safePath from @comis/core for all file write paths.
 *
 * @module
 */

import * as fs from "node:fs";
import * as os from "node:os";
import { stringify } from "yaml";
import { safePath } from "@comis/core";
import { ok, err, type Result } from "@comis/shared";
import type { WizardResult } from "./flow-types.js";
import { PROVIDER_ENV_KEYS, CHANNEL_ENV_KEYS } from "./flow-types.js";

/**
 * Write a config.yaml file from wizard results.
 *
 * Builds a config object matching AppConfigSchema shape and serializes
 * it to YAML via the yaml library. Returns the written file path.
 */
export function writeWizardConfig(
  result: WizardResult,
  configDir: string,
): Result<string, Error> {
  try {
    const defaultDir = os.homedir() + "/.comis";

    const config: Record<string, unknown> = {
      logLevel: "info",
      dataDir: result.dataDir ?? defaultDir,
      agents: {
        default: {
          name: result.agentName,
          provider: result.provider,
          model: result.model ?? getDefaultModel(result.provider),
        },
      },
    };

    // Gateway section
    const gatewayConfig: Record<string, unknown> = {
      enabled: result.gatewayEnabled ?? false,
    };
    if (result.gatewayEnabled) {
      gatewayConfig.host = result.gatewayHost ?? "127.0.0.1";
      gatewayConfig.port = result.gatewayPort ?? 3000;
      if (result.gatewayToken) {
        gatewayConfig.tokens = [
          { id: "default", secret: "${COMIS_GATEWAY_TOKEN}", scopes: ["*"] },
        ];
      }
    }
    config.gateway = gatewayConfig;

    // Channels section
    if (result.channels && result.channels.length > 0) {
      const channels: Record<string, unknown> = {};
      for (const ch of result.channels) {
        const entry: Record<string, unknown> = { enabled: true };
        // Use ${VAR} substitution — credentials go in .env, not config.yaml
        if (ch.type === "telegram" && ch.botToken) entry.botToken = "${TELEGRAM_BOT_TOKEN}";
        if (ch.type === "discord" && ch.botToken) entry.botToken = "${DISCORD_BOT_TOKEN}";
        if (ch.type === "slack" && ch.botToken) entry.botToken = "${SLACK_BOT_TOKEN}";
        if (ch.type === "slack" && ch.apiKey) entry.signingSecret = "${SLACK_SIGNING_SECRET}";
        if (ch.type === "whatsapp" && ch.botToken) entry.accessToken = "${WHATSAPP_ACCESS_TOKEN}";
        if (ch.type === "line" && ch.botToken) entry.channelAccessToken = "${LINE_CHANNEL_ACCESS_TOKEN}";
        if (ch.type === "line" && ch.apiKey) entry.channelSecret = "${LINE_CHANNEL_SECRET}";
        // Generic fallback for other channel types
        if (ch.botToken && !entry.botToken && !entry.accessToken && !entry.channelAccessToken) {
          entry.botToken = `\${${ch.type.toUpperCase()}_BOT_TOKEN}`;
        }
        if (ch.apiKey && !entry.signingSecret && !entry.channelSecret) {
          entry.apiKey = `\${${ch.type.toUpperCase()}_API_KEY}`;
        }
        if (ch.appToken) entry.appToken = `\${${ch.type.toUpperCase()}_APP_TOKEN}`;
        channels[ch.type] = entry;
      }
      config.channels = channels;
    }

    const yaml = stringify(config, { lineWidth: 0 });

    fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
    const configPath = safePath(configDir, "config.yaml");
    fs.writeFileSync(configPath, yaml, "utf-8");

    return ok(configPath);
  } catch (e) {
    return err(e instanceof Error ? e : new Error(String(e)));
  }
}

/**
 * Write a .env file from wizard results.
 *
 * Sets the appropriate provider API key environment variable.
 * File is written with mode 0o600 (owner read/write only).
 */
export function writeWizardEnv(
  result: WizardResult,
  configDir: string,
): Result<string, Error> {
  try {
    const lines: string[] = ["# Comis secrets -- generated by init wizard"];

    if (result.provider && result.apiKey) {
      const envKey = PROVIDER_ENV_KEYS[result.provider];
      if (envKey) {
        lines.push(`${envKey}=${result.apiKey}`);
      }
    }

    // Write channel credentials to .env
    if (result.channels) {
      for (const ch of result.channels) {
        const envKeys = CHANNEL_ENV_KEYS[ch.type];
        if (ch.botToken && envKeys?.[0]) lines.push(`${envKeys[0]}=${ch.botToken}`);
        if (ch.apiKey && envKeys?.[1]) lines.push(`${envKeys[1]}=${ch.apiKey}`);
        if (ch.appToken) lines.push(`${ch.type.toUpperCase()}_APP_TOKEN=${ch.appToken}`);
      }
    }

    // Write gateway token to .env
    if (result.gatewayToken) {
      lines.push(`COMIS_GATEWAY_TOKEN=${result.gatewayToken}`);
    }

    fs.mkdirSync(configDir, { recursive: true, mode: 0o700 });
    const envPath = safePath(configDir, ".env");
    fs.writeFileSync(envPath, lines.join("\n") + "\n", { mode: 0o600 });

    return ok(envPath);
  } catch (e) {
    return err(e instanceof Error ? e : new Error(String(e)));
  }
}

/** Get a sensible default model for a provider. */
function getDefaultModel(provider: string): string {
  const defaults: Record<string, string> = {
    anthropic: "claude-sonnet-4-5-20250929",
    openai: "gpt-4o",
    google: "gemini-2.0-flash",
    groq: "llama-3.3-70b-versatile",
    ollama: "llama3",
  };
  return defaults[provider] ?? "default";
}
