// SPDX-License-Identifier: Apache-2.0
// @comis/core exports — Domain types (Zod schemas, inferred types, parse functions)

export {
  // NormalizedMessage
  AttachmentSchema,
  INBOUND_MESSAGE_PROVENANCE_CUSTOM_TYPE,
  NormalizedMessageSchema,
  parseMessage,
  parseInboundMessageProvenanceBatch,
  getOriginalInboundMessages,
  getMessageTraceId,
  // NormalizedReaction
  NormalizedReactionSchema,
  parseReaction,
  // MemoryEntry
  TrustLevelSchema,
  MemorySourceSchema,
  MemoryEntrySchema,
  MemoryWriteScopeSchema,
  createMemoryRecallScope,
  resolveMemoryVisibility,
  // Structured extraction + domain target
  ExtractedEntitySchema,
  StructuredMemorySchema,
  MemoryExtractionResultSchema,
  MemoryEntitySchema,
  // AgentResponse
  ToolCallSchema,
  TokenUsageSchema,
  AgentResponseSchema,
  // SessionKey
  SessionKeySchema,
  parseSessionKey,
  formatSessionKey,
  parseFormattedSessionKey,
  SessionStoreError,
  // Poll
  PollInputSchema,
  PollOptionResultSchema,
  NormalizedPollResultSchema,
  normalizePollDurationHours,
  // Rich Messaging
  RichButtonSchema,
  RichCardFieldSchema,
  RichCardSchema,
  RichEffectSchema,
  // Approval Request
  ApprovalRequestSchema,
  ApprovalResolutionSchema,
  SerializedApprovalRequestSchema,
  SerializedApprovalCacheEntrySchema,
  // CredentialMapping
  InjectionTypeSchema,
  CredentialMappingSchema,
  // SecretRef
  SecretRefSchema,
  isSecretRef,
  SecretRefOrStringSchema,
  isMcpInstructionTextSafe,
  parseWorkspacePolicySnapshot,
  // DeliveryOrigin
  DeliveryOriginSchema,
  createDeliveryOrigin,
  DeliveryStatusSchema,
  DeliveryFailureStageSchema,
  parseDeliveryFailureStage,
  parseDeliveryStatus,
  // ExecutionGraph
  NodeStatusSchema,
  GraphStatusSchema,
  GraphNodeSchema,
  NodeExecutionStateSchema,
  ExecutionGraphSchema,
  GraphValidationError,
  parseExecutionGraph,
  topologicalSort,
  validateAndSortGraph,
  // Subagent context lifecycle
  SubagentResultSchema,
  SubagentEndReasonSchema,
  parseSubagentResult,
  SubagentContextConfigSchema,
  // Node type driver
  NodeTypeIdSchema,
  // Model compat config
  ToolSchemaProfileSchema,
  ToolCallArgumentsEncodingSchema,
  ModelCompatConfigSchema,
  // Provider capabilities
  ProviderFamilySchema,
  TranscriptToolCallIdModeSchema,
  ProviderCapabilitiesSchema,
  // Sub-agent tool governance
  SUB_AGENT_TOOL_DENYLIST,
  SUB_AGENT_TOOL_PROFILES,
  SUB_AGENT_TOOL_GROUPS,
  RequiredToolsUnreachableError,
  toolReachableGroups,
  computeReachableToolNames,
  // RPC typed-refusal classification (single source of truth)
  classifyTypedRpcError,
  // MemoryExportEnvelope
  MemoryExportEnvelopeSchema,
  MemoryExportEntrySchema,
  parseMemoryExportEnvelope,
  ChannelEndpointSchema,
  ConversationScopeSchema,
  ResolvedTurnScopeSchema,
  ConversationRefSchema,
  ConversationLocatorSchema,
  createConversationRef,
  createConversationLocator,
  conversationScopeToSessionKey,
  CanonicalLocaleSchema,
  AgentExecutionAbortReasonSchema,
  ModelResolutionSourceSchema,
  AgentTurnExecutionOutcomeSchema,
  classifyAgentTurnExecutionOutcome,
} from "../domain/index.js";

export { BackgroundTaskOriginSchema } from "../domain/background-task-origin.js";
export type { BackgroundTaskOrigin } from "../domain/background-task-origin.js";

export { KEYLESS_PROVIDER_TYPES, KEYLESS_API_KEY_SENTINEL } from "../provider/keyless-providers.js";

export type {
  Attachment,
  OriginalInboundMessage,
  NormalizedMessage,
  NormalizedReaction,
  TrustLevel,
  MemoryEntry,
  MemoryVisibilityRequest,
  MemoryWriteScope,
  MemoryRecallScope,
  // MemoryExportEnvelope
  MemoryExportEnvelope,
  MemoryExportEntry,
  // Structured extraction + domain target
  MemorySource,
  ExtractedEntity,
  StructuredMemory,
  MemoryExtractionResult,
  MemoryEntity,
  ToolCall,
  TokenUsage,
  AgentResponse,
  SessionKey,
  PollInput,
  NormalizedPollResult,
  PollOptionResult,
  RichButton,
  RichCard,
  RichEffect,
  ApprovalRequest,
  ApprovalCallbackOwner,
  ApprovalResolution,
  SerializedApprovalRequest,
  SerializedApprovalCacheEntry,
  InjectionType,
  CredentialMapping,
  SecretRef,
  McpInstructionBlock,
  InstructionSourceKind,
  InstructionTrust,
  InstructionStability,
  InstructionSection,
  WorkspacePolicySnapshot,
  ResponseLocaleSource,
  ResponseLocalePolicy,
  DeliveryOrigin,
  DeliveryStatus,
  DeliveryFailureStage,
  // ExecutionGraph
  NodeStatus,
  GraphStatus,
  GraphNode,
  NodeExecutionState,
  ExecutionGraph,
  ValidatedGraph,
  // Subagent context lifecycle
  SubagentResult,
  SubagentEndReason,
  SpawnPacket,
  CondensedResult,
  SubAgentSpawnPreparedEvent,
  SubAgentSpawnRejectedEvent,
  SubAgentSpawnStartedEvent,
  SubAgentResultCondensedEvent,
  SubAgentLifecycleEndedEvent,
  SubAgentContextCompactedEvent,
  SubagentContextConfig,
  // Node type driver
  NodeTypeId,
  NodeTypeDriver,
  NodeDriverAction,
  NodeDriverContext,
  // Model compat config
  ToolSchemaProfile,
  ToolCallArgumentsEncoding,
  ModelCompatConfig,
  // Provider capabilities
  ProviderFamily,
  TranscriptToolCallIdMode,
  ProviderCapabilities,
  // Sub-agent tool governance
  UnreachableToolEntry,
  ChannelEndpoint,
  PrincipalScope,
  ConversationScope,
  ResolvedTurnScope,
  ConversationRef,
  ConversationLocator,
  AgentExecutionFinishReason,
  AgentExecutionAbortReason,
  ModelResolutionSource,
  ExecutionSideEffectSummary,
  AgentTurnExecutionOutcome,
} from "../domain/index.js";
