// SPDX-License-Identifier: Apache-2.0
// @comis/core exports — Port interfaces (hexagonal architecture boundaries)
// Runtime values that previously lived under core/src/ports/ now live in
// non-ports/ home modules. The public surface stays byte-identical — only
// the re-export targets shifted.

export { ChannelCapabilitySchema } from "../domain/channel-capability.js";
export { createNoOpDeliveryQueue } from "../delivery/no-op-delivery-queue.js";
export { createNoOpDeliveryMirror } from "../delivery/no-op-delivery-mirror.js";
export { createNoOpCapabilityPort } from "../tool-capability/no-op-tool-capability.js";
export { validateProfileId, PROFILE_ID_RE } from "../security/profile-id.js";
export type {
  ChannelPort,
  MessageHandler,
  SendMessageOptions,
  FetchMessagesOptions,
  FetchedMessage,
  AttachmentPayload,
  ChannelPluginPort,
  ChannelCapability,
  ChannelStatus,
  MemoryPort,
  MemorySearchOptions,
  MemorySearchResult,
  MemoryUpdateFields,
  SkillPort,
  SkillPermissions,
  SkillInput,
  SkillOutput,
  SkillManifest,
  EmbeddingPort,
  ContextStorePort,
  CtxConversationRow,
  CtxMessageRow,
  CtxMessagePartRow,
  CtxSummaryRow,
  CtxSummaryMessageRow,
  CtxSummaryParentRow,
  CtxContextItemRow,
  CtxLargeFileRow,
  CtxExpansionGrantRow,
  SessionStorePort,
  SessionData,
  SessionListEntry,
  SessionDetailedEntry,
  FileLockPort,
  LockOptions,
  LockError,
  ComputeDailyResetNextRun,
  TranscriptionPort,
  TranscriptionOptions,
  TranscriptionResult,
  TTSPort,
  TTSOptions,
  TTSResult,
  ImageAnalysisPort,
  ImageAnalysisOptions,
  VisionRequest,
  VideoRequest,
  VisionResult,
  VisionProvider,
  ResolvedMedia,
  MediaResolverPort,
  FileClassification,
  FileExtractionErrorKind,
  FileExtractionError,
  FileExtractionInput,
  FileExtractionResult,
  FileExtractionPort,
  HookName,
  ModifyingHookName,
  VoidHookName,
  HookHandlerMap,
  HookBeforeAgentStartEvent,
  HookBeforeAgentStartContext,
  HookBeforeAgentStartResult,
  HookBeforeCompactionEvent,
  HookBeforeCompactionContext,
  HookBeforeCompactionResult,
  HookAfterCompactionEvent,
  HookAfterCompactionContext,
  HookSessionStartEvent,
  HookSessionStartContext,
  HookSessionEndEvent,
  HookSessionEndContext,
  HookGatewayStartEvent,
  HookGatewayStartContext,
  HookGatewayStopEvent,
  HookGatewayStopContext,
  PluginPort,
  PluginRegistryApi,
  RegisteredHook,
  DeviceIdentity,
  DeviceIdentityPort,
  PairingRequest,
  PairedDevice,
  OutputGuardPort,
  OutputGuardFinding,
  OutputGuardResult,
  SecretStorePort,
  SecretMetadata,
  CredentialMappingPort,
  OAuthCredentialStorePort,
  OAuthProfile,
  DeliveryQueuePort,
  DeliveryQueueEntry,
  DeliveryQueueEnqueueInput,
  DeliveryQueueStatusCounts,
  DeliveryMirrorPort,
  DeliveryMirrorEntry,
  DeliveryMirrorRecordInput,
  Provider,
  ImageGenInput,
  ImageGenOutput,
  ImageGenerationPort,
  ToolCapabilityPort,
  PromptSkillCapability,
  CapabilitySourceRef,
  ClusterConfig,
  McpServerHint,
  SkillHint,
  ClockPort,
  EnvPort,
  TimerPort,
  TimerHandle,
} from "../ports/index.js";
