// SPDX-License-Identifier: Apache-2.0
// @comis/core exports — Port interfaces (hexagonal architecture boundaries)
// Runtime values that previously lived under core/src/ports/ now live in
// non-ports/ home modules. The public surface stays byte-identical — only
// the re-export targets shifted.

export { ChannelCapabilitySchema } from "../domain/channel-capability.js";
export { createNoOpDeliveryQueue } from "../delivery/no-op-delivery-queue.js";
export { createNoOpDeliveryMirror } from "../delivery/no-op-delivery-mirror.js";
export { createNoOpCapabilityPort } from "../tool-capability/no-op-tool-capability.js";
export { validateProfileId, PROFILE_ID_RE } from "../security/profile-id.js";
export type {
  ChannelPort,
  MessageHandler,
  SendMessageOptions,
  FetchMessagesOptions,
  FetchedMessage,
  AttachmentPayload,
  ChannelPluginPort,
  ChannelCapability,
  ChannelStatus,
  MemoryPort,
  MemorySearchOptions,
  MemorySearchResult,
  EmbeddingPort,
  RerankerPort,
  MemoryEntityStore,
  EntityScope,
  EntityRow,
  MemoryPinnedStore,
  MemoryTemporalStore,
  MemoryEmbeddingStore,
  MemoryCausalStore,
  CausalScope,
  TripleStorePort,
  TripleScope,
  TripleTrust,
  TripleInput,
  UserRepresentationStore,
  UserRepresentationScope,
  UserRepresentationTrust,
  UserRepresentationEntry,
  UserRepresentationInput,
  TunedAlphaStore,
  TunedAlphaScope,
  TunedAlphaVector,
  MemoryLifecyclePort,
  MemoryLifecycleScope,
  MemoryTier,
  LifecycleSweepReport,
  RelationshipStore,
  RelationshipScope,
  RelationshipTrust,
  RelationshipEntry,
  RelationshipInput,
  MemoryUsefulnessStore,
  UsefulnessScope,
  UsefulnessSignal,
  MemoryConsolidationStore,
  ConsolidationCandidate,
  ConsolidationPlan,
  ConsolidationFoldPlan,
  SessionStorePort,
  SessionData,
  SessionListEntry,
  SessionDetailedEntry,
  ContextStorePort,
  ContextBrowsePort,
  LcdProvenanceReadStore,
  LcdMessage,
  LcdMessagePart,
  LcdPartMetadata,
  LcdPartKind,
  LcdRole,
  ContextStoreScope,
  ContextBrowseScope,
  LcdConversationSummary,
  LcdConversationPage,
  AppendMessageInput,
  LcdSummary,
  LcdSummaryKind,
  LcdContextItem,
  LcdRefKind,
  LcdSearchHit,
  LcdSearchResult,
  AppendSummaryInput,
  AppendCondensedSummaryInput,
  AppendProvenanceInput,
  FileLockPort,
  LockOptions,
  LockError,
  ComputeDailyResetNextRun,
  TranscriptionPort,
  TranscriptionOptions,
  TranscriptionResult,
  TTSPort,
  TTSOptions,
  TTSResult,
  ImageAnalysisPort,
  ImageAnalysisOptions,
  VisionRequest,
  VideoRequest,
  VisionResult,
  VisionProvider,
  ResolvedMedia,
  MediaResolverPort,
  FileClassification,
  FileExtractionErrorKind,
  FileExtractionError,
  FileExtractionInput,
  FileExtractionResult,
  FileExtractionPort,
  HookName,
  ModifyingHookName,
  VoidHookName,
  HookHandlerMap,
  HookBeforeAgentStartEvent,
  HookBeforeAgentStartContext,
  HookBeforeAgentStartResult,
  HookBeforeCompactionEvent,
  HookBeforeCompactionContext,
  HookBeforeCompactionResult,
  HookAfterCompactionEvent,
  HookAfterCompactionContext,
  HookSessionStartEvent,
  HookSessionStartContext,
  HookSessionEndEvent,
  HookSessionEndContext,
  HookGatewayStartEvent,
  HookGatewayStartContext,
  HookGatewayStopEvent,
  HookGatewayStopContext,
  PluginPort,
  PluginRegistryApi,
  RegisteredHook,
  OutputGuardPort,
  OutputGuardFinding,
  OutputGuardResult,
  SecretStorePort,
  SecretMetadata,
  OAuthCredentialStorePort,
  OAuthProfile,
  DeliveryQueuePort,
  DeliveryQueueEntry,
  DeliveryQueueEnqueueInput,
  DeliveryQueueStatusCounts,
  DeliveryMirrorPort,
  DeliveryMirrorEntry,
  DeliveryMirrorRecordInput,
  ImageGenInput,
  ImageGenOutput,
  ImageGenerationPort,
  ToolCapabilityPort,
  PromptSkillCapability,
  CapabilitySourceRef,
  ClusterConfig,
  McpServerHint,
  SkillHint,
  ClockPort,
  EnvPort,
  TimerPort,
  TimerHandle,
  CaManagerPort,
  EgressControlPort,
  EgressMaterialization,
} from "../ports/index.js";

// LCD parts <-> pi-ai Message codec (v2.12, Phase 127). Runtime VALUES (not
// types) — the pure round-trip functions the memory adapter (Plan 04) and
// Phase 128 ingest consume. The port + DTO TYPES are in the export-type block
// above; these two functions are the value seam.
export { messageToParts, partsToMessage } from "../context-store/index.js";
