// SPDX-License-Identifier: Apache-2.0
/** Bounded acceptance and identity reconciliation for offline channel messages. */

import { systemDateFrom } from "@comis/core";
import type { CompletedProvenanceOccurrence } from "./session-message-provenance.js";
import type {
  ExtractedChannelMessage,
  SessionMessagesCoverage,
  SessionMessagesFilter,
  UnparsedSessionMessageReason,
} from "./session-message-report.js";

/** Session channel-id prefixes authored by agents or schedulers. */
const INTERNAL_CHANNEL_ID_RE = /^(cron:|sub-agent:|heartbeat-)/;

/** The reserved sender the queue follow-up trigger injects into real peer sessions. */
const INTERNAL_SENDER_ID = "system";

/** In-process envelope channels whose turns are generated by Comis, not a user. */
const INTERNAL_ENVELOPE_CHANNEL_TYPES = new Set(["background_task", "cross-session"]);

/** Maximum redacted unparsed-record samples returned in one report. */
const MAX_UNPARSED_EVIDENCE = 100;

export interface RankedExtractedChannelMessage extends ExtractedChannelMessage {
  /** File-order tie-breaker, removed from public output. */
  sourceOrder: number;
}

export interface SeenProvenanceIdentity {
  fingerprint: string;
  source: "ledger" | "transcript";
  matched: boolean;
}

export interface PendingUnparsedEvidence {
  reason: UnparsedSessionMessageReason;
  countedAsUnparsed: boolean;
  sessionFile: string;
  sessionKey: string;
  sessionChannelId: string;
  agentId: string;
  timestamp: string | null;
  rawText: string;
}

/** Classify whether a physical inbound identity was authored inside Comis. */
export function classifySessionMessageOrigin(
  sessionChannelId: string,
  channelType: string,
  senderId: string,
): "user" | "internal" {
  return INTERNAL_CHANNEL_ID_RE.test(sessionChannelId) ||
    senderId === INTERNAL_SENDER_ID ||
    INTERNAL_ENVELOPE_CHANNEL_TYPES.has(channelType)
    ? "internal"
    : "user";
}

/** Whether a session channel id is reserved for internal dispatch. */
export function isInternalSessionChannel(sessionChannelId: string): boolean {
  return INTERNAL_CHANNEL_ID_RE.test(sessionChannelId);
}

/** Resolve sender provenance only when the scoped peer and user agree. */
export function trustedSessionSender(
  key: { userId: string; peerId?: string },
): string | undefined {
  return key.peerId !== undefined && key.peerId === key.userId
    ? key.userId
    : undefined;
}

/** Ascending chronological comparator shared by the heap and final output. */
export function compareRankedMessages(
  a: RankedExtractedChannelMessage,
  b: RankedExtractedChannelMessage,
): number {
  return a.epochMs - b.epochMs ||
    a.sessionKey.localeCompare(b.sessionKey) ||
    a.sourceOrder - b.sourceOrder;
}

/** Retain only the globally latest bounded matches in a min-heap. */
export function retainLatestMessage(
  heap: RankedExtractedChannelMessage[],
  message: RankedExtractedChannelMessage,
  limit: number,
  coverage: SessionMessagesCoverage,
): void {
  if (heap.length < limit) {
    heap.push(message);
    let index = heap.length - 1;
    while (index > 0) {
      const parent = Math.floor((index - 1) / 2);
      if (compareRankedMessages(heap[parent]!, heap[index]!) <= 0) break;
      [heap[parent], heap[index]] = [heap[index]!, heap[parent]!];
      index = parent;
    }
    return;
  }

  coverage.conflictCandidateCapReached = true;
  if (compareRankedMessages(message, heap[0]!) <= 0) return;
  heap[0] = message;
  let index = 0;
  while (true) {
    const left = index * 2 + 1;
    const right = left + 1;
    let oldest = index;
    if (left < heap.length && compareRankedMessages(heap[left]!, heap[oldest]!) < 0) {
      oldest = left;
    }
    if (right < heap.length && compareRankedMessages(heap[right]!, heap[oldest]!) < 0) {
      oldest = right;
    }
    if (oldest === index) return;
    [heap[index], heap[oldest]] = [heap[oldest]!, heap[index]!];
    index = oldest;
  }
}

interface ProvenanceAcceptanceContext {
  occurrence: CompletedProvenanceOccurrence;
  source: "ledger" | "transcript";
  sessionFile: string;
  seenIdentities: Map<string, SeenProvenanceIdentity>;
  conflictedIdentities: Set<string>;
  inferredChannels: Map<string, Set<string>>;
  pendingEvidence: PendingUnparsedEvidence[];
  sessionChannelId: string;
  formattedKey: string;
  agentId: string;
  filter: SessionMessagesFilter;
  matches: RankedExtractedChannelMessage[];
  candidateLimit: number;
  coverage: SessionMessagesCoverage;
  sourceOrder: number;
}

/** Remove an identity that became ambiguous and restore the bounded min-heap. */
function removeConflictedIdentity(
  matches: RankedExtractedChannelMessage[],
  identity: string,
  candidateLimit: number,
  coverage: SessionMessagesCoverage,
): boolean {
  const retained = matches.filter((message) =>
    message.messageId === null ||
    JSON.stringify([message.channelType, message.chatId, message.messageId]) !== identity);
  if (retained.length === matches.length) return false;
  matches.length = 0;
  for (const message of retained) {
    retainLatestMessage(matches, message, candidateLimit, coverage);
  }
  return true;
}

/** Accept one complete occurrence only after every repeated identity agrees. */
export function acceptProvenanceOccurrence(context: ProvenanceAcceptanceContext): number {
  const {
    occurrence,
    source,
    sessionFile,
    seenIdentities,
    conflictedIdentities,
    sessionChannelId,
    formattedKey,
    agentId,
    filter,
    matches,
    candidateLimit,
    coverage,
  } = context;
  const occurrenceIdentities = new Map<string, string>();
  for (const original of occurrence.messages) {
    const identity = JSON.stringify([original.channelType, original.channelId, original.id]);
    const fingerprint = JSON.stringify(original);
    if (conflictedIdentities.has(identity)) {
      coverage.invalidProvenanceRecords++;
      return context.sourceOrder;
    }
    const priorInOccurrence = occurrenceIdentities.get(identity);
    if (priorInOccurrence !== undefined && priorInOccurrence !== fingerprint) {
      coverage.invalidProvenanceRecords++;
      coverage.provenanceConflicts++;
      conflictedIdentities.add(identity);
      const prior = seenIdentities.get(identity);
      if (prior?.matched === true) coverage.matchedBeforeLimit--;
      removeConflictedIdentity(matches, identity, candidateLimit, coverage);
      retainPendingEvidence(context.pendingEvidence, {
        reason: "duplicate_conflict",
        countedAsUnparsed: false,
        sessionFile,
        sessionKey: formattedKey,
        sessionChannelId,
        agentId,
        timestamp: systemDateFrom(occurrence.recordedAt).toISOString(),
        rawText: original.text,
      }, coverage);
      return context.sourceOrder;
    }
    occurrenceIdentities.set(identity, fingerprint);
  }

  let sourceOrder = context.sourceOrder;
  for (const original of occurrence.messages) {
    const identity = JSON.stringify([original.channelType, original.channelId, original.id]);
    const fingerprint = JSON.stringify(original);
    const prior = seenIdentities.get(identity);
    if (prior !== undefined && prior.fingerprint === fingerprint) {
      coverage.duplicateProvenanceMessagesExcluded++;
      if (source === "ledger" && prior.source === "transcript") {
        seenIdentities.set(identity, { ...prior, source: "ledger" });
      }
      continue;
    }
    if (prior !== undefined && prior.source !== source) {
      coverage.duplicateProvenanceMessagesExcluded++;
      coverage.mirrorDifferencesReconciled++;
      if (source === "transcript") continue;
      if (prior.matched) coverage.matchedBeforeLimit--;
      removeConflictedIdentity(matches, identity, candidateLimit, coverage);
    } else if (prior !== undefined) {
      coverage.invalidProvenanceRecords++;
      coverage.provenanceConflicts++;
      conflictedIdentities.add(identity);
      if (prior.matched) coverage.matchedBeforeLimit--;
      removeConflictedIdentity(matches, identity, candidateLimit, coverage);
      seenIdentities.delete(identity);
      retainPendingEvidence(context.pendingEvidence, {
        reason: "duplicate_conflict",
        countedAsUnparsed: false,
        sessionFile,
        sessionKey: formattedKey,
        sessionChannelId,
        agentId,
        timestamp: systemDateFrom(occurrence.recordedAt).toISOString(),
        rawText: original.text,
      }, coverage);
      continue;
    }

    const channels = context.inferredChannels.get(sessionFile) ?? new Set<string>();
    channels.add(original.channelType);
    context.inferredChannels.set(sessionFile, channels);
    const epochMs = occurrence.recordedAt;
    let matched = true;
    if (filter.sinceMs !== undefined && epochMs < filter.sinceMs) matched = false;
    if (filter.untilMs !== undefined && epochMs >= filter.untilMs) matched = false;
    if (filter.channel !== undefined && filter.channel !== original.channelType) matched = false;
    if (filter.sender !== undefined && filter.sender !== original.senderId) matched = false;
    const origin = classifySessionMessageOrigin(
      sessionChannelId,
      original.channelType,
      original.senderId,
    );
    if (origin === "internal" && filter.includeInternal !== true) {
      coverage.internalExcluded++;
      matched = false;
    }
    seenIdentities.set(identity, { fingerprint, source, matched });
    if (!matched) continue;
    coverage.matchedBeforeLimit++;
    const timestamp = systemDateFrom(epochMs).toISOString();
    retainLatestMessage(matches, {
      messageId: original.id,
      timestamp,
      epochMs,
      channelType: original.channelType,
      senderId: original.senderId,
      envelopeTime: timestamp,
      text: original.text,
      redactions: 0,
      agentId,
      chatId: original.channelId,
      sessionKey: formattedKey,
      origin,
      sourceOrder: sourceOrder++,
    }, candidateLimit, coverage);
  }
  return sourceOrder;
}

/** Retain a bounded raw sample for redacted/classified report assembly. */
export function retainPendingEvidence(
  pending: PendingUnparsedEvidence[],
  evidence: PendingUnparsedEvidence,
  coverage: SessionMessagesCoverage,
): void {
  if (pending.length >= MAX_UNPARSED_EVIDENCE) {
    coverage.unparsedEvidenceCapped++;
    return;
  }
  pending.push(evidence);
}

/** Resolve a message limit without widening invalid direct-library inputs. */
export function resolveMessageLimit(
  filter: SessionMessagesFilter,
  maxMessages: number,
): { requested: number | null; effective: number; rejected: boolean } {
  if (filter.limit === undefined) {
    return { requested: maxMessages, effective: maxMessages, rejected: false };
  }
  if (
    !Number.isSafeInteger(filter.limit) ||
    filter.limit <= 0 ||
    filter.limit > maxMessages
  ) {
    return {
      requested: Number.isFinite(filter.limit) ? filter.limit : null,
      effective: 0,
      rejected: true,
    };
  }
  return {
    requested: filter.limit,
    effective: filter.limit,
    rejected: false,
  };
}
