// SPDX-License-Identifier: Apache-2.0
/* AUTOGENERATED — do not edit. Run `pnpm sdk:generate`. */
/* eslint-disable */
import { invoke, wrapResultRef, callCapSocket } from "./orchestrate-sdk-runtime.js";

// ---------------------------------------------------------------------------
// The discovery surface (progressive disclosure) + one delegating method per
// capability-mapped tool. Each method sends a single `tool.invoke` over the
// cap socket via the runtime shim; high-volume returns are wrapped as a
// ResultRef with in-jail extraction.
// ---------------------------------------------------------------------------

const DESCRIPTORS = [
  {
    "name": "extract_document",
    "capability": "orch:read",
    "summary": "Extract readable text from a document (pdf/docx/…).",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "find",
    "capability": "orch:read",
    "summary": "Find files in the jailed workspace by name/glob.",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "grep",
    "capability": "orch:read",
    "summary": "Search the jailed workspace for a pattern (recursive).",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "jq",
    "capability": "orch:read",
    "summary": "Run a jq expression over JSON (a value or a ResultRef).",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "jsonpath",
    "capability": "orch:read",
    "summary": "Extract a precise value from a JSON ResultRef via JSONPath (no eval).",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "ls",
    "capability": "orch:read",
    "summary": "List a directory in the jailed workspace.",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "mcp",
    "capability": "orch:mcp",
    "summary": "Call an allowlisted connected MCP server's tool: comis_tools.mcp.<server>.<tool>(args). The server/tool set is operator-configured.",
    "example": "const result = await comis_tools.mcp.myserver.mytool({ query: 'hello' });"
  },
  {
    "name": "memory_get",
    "capability": "orch:read",
    "summary": "Fetch a specific memory file by id (self-tenant).",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "memory_search",
    "capability": "orch:read",
    "summary": "Search the agent's long-term memory (self-tenant).",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "read",
    "capability": "orch:read",
    "summary": "Read a file from the jailed workspace (offset/limit).",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "session_search",
    "capability": "orch:read",
    "summary": "Search across the agent's own session history.",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "session_status",
    "capability": "orch:read",
    "summary": "Read the status of one of the agent's sessions.",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "sessions_history",
    "capability": "orch:read",
    "summary": "Read the message history of the agent's own session.",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "sessions_list",
    "capability": "orch:read",
    "summary": "List the agent's own sessions.",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "sql",
    "capability": "orch:read",
    "summary": "Run DuckDB SQL over a CSV/JSONL/JSON ResultRef (daemon-side, read-only).",
    "example": "const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40);"
  },
  {
    "name": "web_fetch",
    "capability": "orch:web",
    "summary": "Fetch a URL's readable content (daemon-side, DNS-pinned).",
    "example": "const hits = await comis_tools.web_search({ query: 'site reliability' }); const top3 = await hits.jq('.[0:3]'); const page = await comis_tools.web_fetch({ url: top3[0].url }); const text = await page.read(0, 200);"
  },
  {
    "name": "web_search",
    "capability": "orch:web",
    "summary": "Search the web (daemon-side, DNS-pinned).",
    "example": "const hits = await comis_tools.web_search({ query: 'site reliability' }); const top3 = await hits.jq('.[0:3]'); const page = await comis_tools.web_fetch({ url: top3[0].url }); const text = await page.read(0, 200);"
  },
  {
    "name": "write",
    "capability": "orch:write",
    "summary": "Write a file into the jailed run workspace (path-confined, run-ephemeral).",
    "example": "await comis_tools.write({ path: 'summary.md', content: '# Findings' });"
  }
];

export const comis_tools = {
  describe() {
    return DESCRIPTORS;
  },
  async extract_document(args) {
    return wrapResultRef(await invoke("extract_document", args));
  },
  async find(args) {
    return invoke("find", args);
  },
  async grep(args) {
    return wrapResultRef(await invoke("grep", args));
  },
  async jq(args) {
    return invoke("jq", args);
  },
  async jsonpath(args) {
    return invoke("jsonpath", args);
  },
  async ls(args) {
    return invoke("ls", args);
  },
  mcp: (() => {
    const isNonToolKey = (k) =>
      typeof k === "symbol" ||
      k === "then" ||
      k === "catch" ||
      k === "finally" ||
      k === "toJSON";
    return new Proxy(
      {},
      {
        get(_serverTarget, server) {
          if (isNonToolKey(server)) return undefined;
          return new Proxy(
            {},
            {
              get(_toolTarget, tool) {
                if (isNonToolKey(tool)) return undefined;
                return (args) =>
                  callCapSocket("tool.invoke", {
                    tool: "mcp",
                    args: { server, tool, args },
                  });
              },
            },
          );
        },
      },
    );
  })(),
  async memory_get(args) {
    return invoke("memory_get", args);
  },
  async memory_search(args) {
    return invoke("memory_search", args);
  },
  async read(args) {
    return wrapResultRef(await invoke("read", args));
  },
  async session_search(args) {
    return invoke("session_search", args);
  },
  async session_status(args) {
    return invoke("session_status", args);
  },
  async sessions_history(args) {
    return invoke("sessions_history", args);
  },
  async sessions_list(args) {
    return invoke("sessions_list", args);
  },
  async sql(args) {
    return invoke("sql", args);
  },
  async web_fetch(args) {
    return wrapResultRef(await invoke("web_fetch", args));
  },
  async web_search(args) {
    return wrapResultRef(await invoke("web_search", args));
  },
  async write(args) {
    return invoke("write", args);
  },
  async message_send(args) {
    return callCapSocket("message.send", args);
  },
  async message_reply(args) {
    return callCapSocket("message.reply", args);
  },
  async message_react(args) {
    return callCapSocket("message.react", args);
  },
};

export default comis_tools;
