# SPDX-License-Identifier: Apache-2.0
# AUTOGENERATED — do not edit. Run `pnpm sdk:generate`.

import json
import os
import socket

_ENV_SOCK = "COMIS_ORCH_SOCKET"
_ENV_LEASE = "COMIS_CAP_LEASE"


def _call_cap_socket(method, params):
    sock_path = os.environ.get(_ENV_SOCK)
    bearer = os.environ.get(_ENV_LEASE)
    if not sock_path or not bearer:
        raise RuntimeError(
            "comis-agent / orchestrate runtime requires "
            "COMIS_ORCH_SOCKET/COMIS_CAP_LEASE — only valid inside an orchestrate jail"
        )
    payload = (
        json.dumps(
            {"bearer": bearer, "method": method, "params": params},
            separators=(",", ":"),
        )
        + "\n"
    )
    sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
    try:
        sock.connect(sock_path)
        sock.sendall(payload.encode("utf-8"))
        buf = b""
        while b"\n" not in buf:
            chunk = sock.recv(65536)
            if not chunk:
                raise RuntimeError("cap socket closed before a complete response line")
            buf += chunk
    finally:
        sock.close()
    reply = json.loads(buf.split(b"\n", 1)[0].decode("utf-8"))
    if reply.get("error") is not None:
        err = reply["error"]
        raise RuntimeError(err if isinstance(err, str) else "capability call failed")
    return reply.get("result")


def _invoke(tool, args=None):
    return _call_cap_socket("tool.invoke", {"tool": tool, "args": args or {}})


class ResultRef:
    """A handle to a high-volume tool return materialized on the jailed workspace.

    The big (untrusted) payload stays on disk as data; only this handle
    re-enters context. Slice it in-jail via grep/jq/sql/jsonpath/read so only
    the requested rows/lines re-enter -- the full payload never does.
    """

    def __init__(self, ref):
        raw = ref if isinstance(ref, dict) else {}
        self.ref = raw.get("ref")
        self.kind = raw.get("kind")
        self.bytes = raw.get("bytes")
        self.rows = raw.get("rows")
        self.schema = raw.get("schema")
        self.preview = raw.get("preview")
        self.expires_at = raw.get("expiresAt")

    def grep(self, pattern):
        return _invoke("grep", {"path": self.ref, "pattern": pattern})

    def jq(self, expr):
        return _invoke("jq", {"path": self.ref, "expr": expr})

    def sql(self, query):
        return _invoke("sql", {"path": self.ref, "query": query})

    def jsonpath(self, expr):
        return _invoke("jsonpath", {"path": self.ref, "expr": expr})

    def read(self, offset=None, limit=None):
        params = {"path": self.ref}
        if offset is not None:
            params["offset"] = offset
        if limit is not None:
            params["limit"] = limit
        return _invoke("read", params)


def _wrap_result_ref(ref):
    return ResultRef(ref)

DESCRIPTORS = [
  {
    "name": "extract_document",
    "capability": "orch:read",
    "summary": "Extract readable text from a document (pdf/docx/…)."
  },
  {
    "name": "find",
    "capability": "orch:read",
    "summary": "Find files in the jailed workspace by name/glob."
  },
  {
    "name": "grep",
    "capability": "orch:read",
    "summary": "Search the jailed workspace for a pattern (recursive)."
  },
  {
    "name": "jq",
    "capability": "orch:read",
    "summary": "Run a jq expression over JSON (a value or a ResultRef)."
  },
  {
    "name": "jsonpath",
    "capability": "orch:read",
    "summary": "Extract a precise value from a JSON ResultRef via JSONPath (no eval)."
  },
  {
    "name": "ls",
    "capability": "orch:read",
    "summary": "List a directory in the jailed workspace."
  },
  {
    "name": "memory_get",
    "capability": "orch:read",
    "summary": "Fetch a specific memory file by id (self-tenant)."
  },
  {
    "name": "memory_search",
    "capability": "orch:read",
    "summary": "Search the agent's long-term memory (self-tenant)."
  },
  {
    "name": "read",
    "capability": "orch:read",
    "summary": "Read a file from the jailed workspace (offset/limit)."
  },
  {
    "name": "session_search",
    "capability": "orch:read",
    "summary": "Search across the agent's own session history."
  },
  {
    "name": "session_status",
    "capability": "orch:read",
    "summary": "Read the status of one of the agent's sessions."
  },
  {
    "name": "sessions_history",
    "capability": "orch:read",
    "summary": "Read the message history of the agent's own session."
  },
  {
    "name": "sessions_list",
    "capability": "orch:read",
    "summary": "List the agent's own sessions."
  },
  {
    "name": "sql",
    "capability": "orch:read",
    "summary": "Run DuckDB SQL over a CSV/JSONL/JSON ResultRef (daemon-side, read-only)."
  },
  {
    "name": "web_fetch",
    "capability": "orch:web",
    "summary": "Fetch a URL's readable content (daemon-side, DNS-pinned)."
  },
  {
    "name": "web_search",
    "capability": "orch:web",
    "summary": "Search the web (daemon-side, DNS-pinned)."
  }
]

def describe():
    return DESCRIPTORS

def extract_document(args=None):
    return _wrap_result_ref(_invoke("extract_document", args))

def find(args=None):
    return _invoke("find", args)

def grep(args=None):
    return _wrap_result_ref(_invoke("grep", args))

def jq(args=None):
    return _invoke("jq", args)

def jsonpath(args=None):
    return _invoke("jsonpath", args)

def ls(args=None):
    return _invoke("ls", args)

def memory_get(args=None):
    return _invoke("memory_get", args)

def memory_search(args=None):
    return _invoke("memory_search", args)

def read(args=None):
    return _wrap_result_ref(_invoke("read", args))

def session_search(args=None):
    return _invoke("session_search", args)

def session_status(args=None):
    return _invoke("session_status", args)

def sessions_history(args=None):
    return _invoke("sessions_history", args)

def sessions_list(args=None):
    return _invoke("sessions_list", args)

def sql(args=None):
    return _invoke("sql", args)

def web_fetch(args=None):
    return _wrap_result_ref(_invoke("web_fetch", args))

def web_search(args=None):
    return _wrap_result_ref(_invoke("web_search", args))
