// SPDX-License-Identifier: Apache-2.0
/* AUTOGENERATED — do not edit. Run `pnpm sdk:generate`. */
/* eslint-disable */

// ---------------------------------------------------------------------------
// ResultRef — a handle to a high-volume tool return materialized on the jailed
// workspace (v8 §23.9). The big (untrusted) payload stays on disk as DATA;
// only this handle re-enters context. Slice it IN-JAIL via the extraction
// methods so just the relevant rows/lines come back (REF-01/02).
// ---------------------------------------------------------------------------

export interface ResultRef {
  /** Workspace-relative path, e.g. "results/abc.jsonl". */
  readonly ref: string;
  /** The materialized content kind. */
  readonly kind: "jsonl" | "json" | "csv" | "html" | "text" | "binary";
  /** Total materialized size in bytes. */
  readonly bytes: number;
  /** Row count for tabular kinds (jsonl/csv), when known. */
  readonly rows?: number;
  /** Column/field names for tabular kinds, when known. */
  readonly schema?: string[];
  /** A tiny bounded head of the content (rides the handle into context). */
  readonly preview: string;
  /** ISO-8601 expiry — the run-GC evicts the file after this. */
  readonly expiresAt: string;
  /** Grep the materialized file for `pattern`; returns the matching lines. */
  grep(pattern: string): Promise<string>;
  /** Run a jq `expr` over the materialized JSON/JSONL; returns the result. */
  jq(expr: string): Promise<unknown>;
  /** Run DuckDB SQL over the materialized CSV/JSONL/JSON; returns the row slice. */
  sql(query: string): Promise<unknown>;
  /** Extract a precise value via a JSONPath `$`-expr (DuckDB json_extract, no eval). */
  jsonpath(expr: string): Promise<unknown>;
  /** Read a slice of the materialized file (`offset`/`limit` lines or bytes). */
  read(offset?: number, limit?: number): Promise<string>;
}

/** A discovery entry returned by `comis_tools.describe()` (the small surface). */
export interface ToolDescriptor {
  /** The tool name (the method on `comis_tools`). */
  readonly name: string;
  /** The capability the tool requires (the cap-map classification). */
  readonly capability: string;
  /** A one-line human summary of what the tool does. */
  readonly summary: string;
  /** A worked calling-pattern example for the tool's capability group. */
  readonly example: string;
}

// ---------------------------------------------------------------------------
// ComisTools — the typed SDK surface. One async method per capability-mapped
// tool (generated from TOOL_CAPABILITY_MAP). `describe()` is the progressive-
// disclosure discovery surface (names + summaries + capability).
// ---------------------------------------------------------------------------

export interface ComisTools {
  /**
   * The discovery surface: list every available tool with its capability and a
   * one-line summary, so the surface is cheap to enumerate before reaching for
   * a specific tool's full types.
   */
  describe(): ToolDescriptor[];
  /** Extract readable text from a document (pdf/docx/…). (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  extract_document(args?: Record<string, unknown>): Promise<ResultRef>;
  /** Find files in the jailed workspace by name/glob. (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  find(args?: Record<string, unknown>): Promise<unknown>;
  /** Search the jailed workspace for a pattern (recursive). (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  grep(args?: Record<string, unknown>): Promise<ResultRef>;
  /** Run a jq expression over JSON (a value or a ResultRef). (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  jq(args?: Record<string, unknown>): Promise<unknown>;
  /** Extract a precise value from a JSON ResultRef via JSONPath (no eval). (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  jsonpath(args?: Record<string, unknown>): Promise<unknown>;
  /** List a directory in the jailed workspace. (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  ls(args?: Record<string, unknown>): Promise<unknown>;
  /** Call an allowlisted connected MCP server's tool: comis_tools.mcp.<server>.<tool>(args). The server/tool set is operator-configured. (capability: orch:mcp) Example: const result = await comis_tools.mcp.myserver.mytool({ query: 'hello' }); */
  mcp: Record<string, Record<string, (args?: Record<string, unknown>) => Promise<unknown>>>;
  /** Fetch a specific memory file by id (self-tenant). (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  memory_get(args?: Record<string, unknown>): Promise<unknown>;
  /** Search the agent's long-term memory (self-tenant). (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  memory_search(args?: Record<string, unknown>): Promise<unknown>;
  /** Read a file from the jailed workspace (offset/limit). (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  read(args?: Record<string, unknown>): Promise<ResultRef>;
  /** Search across the agent's own session history. (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  session_search(args?: Record<string, unknown>): Promise<unknown>;
  /** Read the status of one of the agent's sessions. (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  session_status(args?: Record<string, unknown>): Promise<unknown>;
  /** Read the message history of the agent's own session. (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  sessions_history(args?: Record<string, unknown>): Promise<unknown>;
  /** List the agent's own sessions. (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  sessions_list(args?: Record<string, unknown>): Promise<unknown>;
  /** Run DuckDB SQL over a CSV/JSONL/JSON ResultRef (daemon-side, read-only). (capability: orch:read) Example: const ref = await comis_tools.grep({ path: 'logs/app.jsonl', pattern: 'ERROR' }); const rows = await ref.jq('.[0:20]'); const head = await ref.read(0, 40); */
  sql(args?: Record<string, unknown>): Promise<unknown>;
  /** Fetch a URL's readable content (daemon-side, DNS-pinned). (capability: orch:web) Example: const hits = await comis_tools.web_search({ query: 'site reliability' }); const top3 = await hits.jq('.[0:3]'); const page = await comis_tools.web_fetch({ url: top3[0].url }); const text = await page.read(0, 200); */
  web_fetch(args?: Record<string, unknown>): Promise<ResultRef>;
  /** Search the web (daemon-side, DNS-pinned). (capability: orch:web) Example: const hits = await comis_tools.web_search({ query: 'site reliability' }); const top3 = await hits.jq('.[0:3]'); const page = await comis_tools.web_fetch({ url: top3[0].url }); const text = await page.read(0, 200); */
  web_search(args?: Record<string, unknown>): Promise<ResultRef>;
}

/** The singleton typed SDK the jailed script imports. */
export declare const comis_tools: ComisTools;
export default comis_tools;
